name: "Bug Report"
description: "Press to file a bug report!""
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: >-
        Please, take a moment to fill out this form!
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Briefly tell me, what is wrong.
      placeholder: Minecraft crashes when I open a chest
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Write step by step what needs to be done to reproduce the problem
      placeholder: >-
        1. Open Minecraft
        2. Open a singleplayer world
        3. Open a chest
        4. Minecraft crashes
    validations:
      required: true
  - type: dropdown
    id: client-or-server
    attributes:
      label: Client or server?
      description: Which side are you running?
      options:
        - Client
        - Server
      default: Client
    validations:
      required: true
  - type: dropdown
    id: mc-version
    attributes:
      label: Minecraft version
      description: What version of Minecraft did you run?
      options:
        - Forge 1.21.1
        - Fabric 1.21.1
        - Neoforge 1.21.1
        - Forge 1.20.6
        - Fabric 1.20.6
        - Neoforge 1.20.6
        - Forge 1.20.4
        - Fabric 1.20.4
        - Neoforge 1.20.4
        - Forge 1.20.1
        - Fabric 1.20.1
        - Forge 1.19.2
        - Fabric 1.19.2
        - Forge 1.18.2
        - Fabric 1.18.2
        - Forge 1.16.5
        - Fabric 1.16.5
        - Forge 1.16.1
        - Fabric 1.16.1
        - Forge 1.14.4
        - Fabric 1.14.4
        - Forge 1.12.2
        - Forge 1.8.9
      default: 0
    validations:
      required: true
  - type: dropdown
    id: mod-version
    attributes:
      label: Mod version
      description: What version of MWAPI did you use?
      options:
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Minecraft logs
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!