name: "Сообщение о баге"
description: "Нажмите, чтобы сообщить о баге!"
title: "[Баг]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ###### [English](https://github.com/vpgel/Minecraft-World-API/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml&title=%5BBug%5D%3A+) | Русский
        Пожалуйста, потратьте немного времени, чтобы заполнить эту форму!
  - type: textarea
    id: bug-description
    attributes:
      label: "Описание бага"
      description: "Вкратце расскажите, что не так."
      placeholder: "Майнкрафт вылетает, когда я открываю cундук"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Шаги воспроизведения бага"
      description: "Напишите пошагово, что нужно сделать, чтобы получить баг"
      placeholder: |
        1. Открыть Майнкрафт
        2. Зайти в одиночный мир
        3. Открыть сундук
        4. Майнкрафт вылетает
    validations:
      required: true
  - type: dropdown
    id: client-or-server
    attributes:
      label: "Клиент или сервер?"
      description: "На какой платформе возникает ошибка?"
      options:
        - Клиент Майнкрафта
        - Сервер Майнкрафта
      default: 1
    validations:
      required: true
  - type: dropdown
    id: mc-version
    attributes:
      label: "Версия Майнкрафта"
      description: "Какую версию майнкрафта вы запускали?"
      options:
        - Forge 1.21.1
        - Fabric 1.21.1
        - Neoforge 1.21.1
        - Forge 1.20.6
        - Fabric 1.20.6
        - Neoforge 1.20.6
        - Forge 1.20.4
        - Fabric 1.20.4
        - Neoforge 1.20.4
        - Forge 1.20.1
        - Fabric 1.20.1
        - Forge 1.19.2
        - Fabric 1.19.2
        - Forge 1.18.2
        - Fabric 1.18.2
        - Forge 1.16.5
        - Fabric 1.16.5
        - Forge 1.16.1
        - Fabric 1.16.1
        - Forge 1.14.4
        - Fabric 1.14.4
        - Forge 1.12.2
        - Forge 1.8.9
      default: 0
    validations:
      required: true
  - type: dropdown
    id: mod-version
    attributes:
      label: "Версия мода"
      description: "Какую версию MWAPI вы использовали?"
      options:
        - Нет версий
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Вывод журнала Майнкрафта"
      description: "Пожалуйста, скопируйте и вставьте любой соответствующий вывод журнала. Он будет автоматически отформатирован в код, поэтому нет необходимости в обратных кавычках."
      render: shell
  - type: markdown
    attributes:
      value: |
        Спасибо вам за то, что потратили время и заполнили эту форму!